// This is a list of all available characters from the Marvel API. I will use this to validate searches and to autocomplete searches to make things easier on the user. See the character-log.js file for information on how this information was found and collected. The names were set to lower case to make it easier to remove case sensitivity from searches.

const characters = [
    "3-d man",
    "a-bomb (has)",
    "a.i.m.",
    "aaron stack",
    "abomination (emil blonsky)",
    "abomination (ultimate)",
    "absorbing man",
    "abyss",
    "abyss (age of apocalypse)",
    "adam destine",
    "adam warlock",
    "aegis (trey rollins)",
    "agent brand",
    "agent x (nijo)",
    "agent zero",
    "agents of atlas",
    "aginar",
    "air-walker (gabriel lan)",
    "ajak",
    "ajaxis",
    "akemi",
    "alain",
    "albert cleary",
    "albion",
    "alex power",
    "alex wilder",
    "alexa mendez",
    "alexander pierce",
    "alice",
    "alicia masters",
    "alpha flight",
    "alpha flight (ultimate)",
    "alvin maker",
    "amadeus cho",
    "amanda sefton",
    "amazoness",
    "american eagle (jason strongbow)",
    "amiko",
    "amora",
    "amphibian (earth-712)",
    "amun",
    "ancient one",
    "ancient one (ultimate)",
    "angel (thomas halloway)",
    "angel (ultimate)",
    "angel (warren worthington iii)",
    "angela (aldrif odinsdottir)",
    "anita blake",
    "anne marie hoag",
    "annihilus",
    "anole",
    "ant-man (eric o'grady)",
    "ant-man (scott lang)",
    "anthem",
    "apocalypse",
    "apocalypse (ultimate)",
    "aqueduct",
    "arachne",
    "araña",
    "arcade",
    "arcana",
    "archangel",
    "arclight",
    "ares",
    "argent",
    "armadillo",
    "armor (hisako ichiki)",
    "armory",
    "arnim zola",
    "arsenic",
    "artiee",
    "asgardian",
    "askew-tronics",
    "asylum",
    "atlas (team)",
    "aurora",
    "avalanche",
    "avengers",
    "avengers (ultimate)",
    "azazel (mutant)",
    "banshee",
    "banshee (theresa rourke)",
    "baron strucker",
    "baron zemo (heinrich zemo)",
    "baron zemo (helmut zemo)",
    "baroness s'bak",
    "barracuda",
    "bart rozum",
    "bastion",
    "batroc the leaper",
    "battering ram",
    "beak",
    "beast",
    "beast (earth-311)",
    "beast (ultimate)",
    "becatron",
    "bedlam",
    "beef",
    "beetle (abner jenkins)",
    "ben grimm",
    "ben parker",
    "ben reilly",
    "ben urich",
    "bengal",
    "beta-ray bill",
    "betty brant",
    "betty ross",
    "beyonder",
    "bi-beast",
    "big bertha",
    "big wheel",
    "bill hollister",
    "bishop",
    "bishop (ultimate)",
    "black bird",
    "black bolt",
    "black bolt (marvel war of heroes)",
    "black cat",
    "black cat (ultimate)",
    "black crow",
    "black knight (sir percy of scandia)",
    "black panther",
    "black panther (ultimate)",
    "black queen",
    "black tarantula",
    "black tom",
    "black widow",
    "black widow (lego marvel super heroes)",
    "black widow (ultimate)",
    "black widow/natasha romanoff (maa)",
    "blackheart",
    "blacklash",
    "blackout",
    "blade",
    "blastaar",
    "blazing skull",
    "blindfold",
    "blink",
    "blizzard",
    "blob",
    "blob (ultimate)",
    "blockbuster",
    "blok",
    "bloke",
    "blonde phantom",
    "bloodaxe",
    "bloodscream",
    "bloodstorm",
    "bloodstrike",
    "blue blade",
    "blue marvel",
    "blue shield",
    "blur",
    "bob, agent of hydra",
    "boom boom",
    "boomer",
    "boomerang",
    "box",
    "bride of nine spiders (immortal weapons)",
    "bromley",
    "brood",
    "brother voodoo",
    "brotherhood of evil mutants",
    "brotherhood of mutants (ultimate)",
    "bruce banner",
    "brute",
    "bucky",
    "bug",
    "bulldozer",
    "bullseye",
    "bushwacker",
    "butterfly",
    "cable",
    "cable (deadpool)",
    "cable (marvel: avengers alliance)",
    "cable (ultimate)",
    "cable (x-men: battle of the atom)",
    "calamity",
    "caliban",
    "callisto",
    "callisto (age of apocalypse)",
    "calypso",
    "cammi",
    "cannonball",
    "cap'n oz",
    "captain america",
    "captain america (house of m)",
    "captain america (lego marvel super heroes)",
    "captain america (marvel war of heroes)",
    "captain america (sam wilson)",
    "captain america (ultimate)",
    "captain america/steve rogers (maa)",
    "captain britain",
    "captain britain (ultimate)",
    "captain cross",
    "captain flint",
    "captain marvel (carol danvers)",
    "captain marvel (genis-vell)",
    "captain marvel (mar-vell)",
    "captain marvel (monica rambeau)",
    "captain marvel (phyla-vell)",
    "captain midlands",
    "captain stacy",
    "captain universe",
    "cardiac",
    "caretaker",
    "cargill",
    "carlie cooper",
    "carmella unuscione",
    "carnage",
    "carnage (ultimate)",
    "carol danvers",
    "carol hines",
    "cassandra nova",
    "catseye",
    "cecilia reyes",
    "celestials",
    "centennial",
    "centurions",
    "cerebro",
    "cerise",
    "ch'od",
    "chamber",
    "chameleon",
    "champions",
    "changeling",
    "charles xavier",
    "charlie campion",
    "chase stein",
    "chat",
    "chimera",
    "chores macgillicudy",
    "christian walker",
    "chronomancer",
    "clandestine",
    "clea",
    "clea (ultimate)",
    "clint barton",
    "cloak",
    "cloud 9",
    "cobalt man",
    "colleen wing",
    "colonel america",
    "colossus",
    "colossus (ultimate)",
    "confederates of the curious",
    "constrictor",
    "contessa (vera vidal)",
    "controller",
    "cornelius",
    "corsair",
    "cosmo (dog)",
    "cottonmouth",
    "count nefaria",
    "countess",
    "crimson crusader",
    "crimson dynamo",
    "crimson dynamo (iron man 3 - the official game)",
    "crimson king",
    "crossbones",
    "crule",
    "crusher hogan",
    "crusher hogan (ultimate)",
    "crystal",
    "cuckoo",
    "curt conners",
    "cuthbert",
    "cyber",
    "cyclops",
    "cyclops (ultimate)",
    "cyclops (x-men: battle of the atom)",
    "cypher",
    "d'ken neramani",
    "dagger",
    "daily bugle",
    "daimon hellstrom",
    "daken",
    "dakota north",
    "damage control",
    "dani moonstar",
    "danny rand",
    "daredevil",
    "daredevil (lego marvel super heroes)",
    "daredevil (marvel heroes)",
    "daredevil (ultimate)",
    "dargo ktor",
    "dark avengers",
    "dark beast",
    "dark phoenix",
    "dark x-men",
    "darkhawk",
    "darkstar",
    "darwin",
    "dazzler",
    "dazzler (ultimate)",
    "deacon frost",
    "dead girl",
    "deadpool",
    "deadpool (deadpool)",
    "deadpool (lego marvel super heroes)",
    "deadpool (x-men: battle of the atom)",
    "death",
    "deathbird",
    "deathcry",
    "deathlok",
    "deathstrike (ultimate)",
    "debra whitman",
    "debrii",
    "deena pilgrim",
    "defenders",
    "demogoblin",
    "destiny",
    "detective soap",
    "deviants",
    "devil dinosaur (devil dinosaur)",
    "devil dinosaur (has)",
    "devos",
    "dexter bennett",
    "diablo",
    "diamondback (rachel leighton)",
    "dinah soar",
    "dirk anger",
    "doc samson",
    "doctor doom",
    "doctor doom (ultimate)",
    "doctor faustus",
    "doctor octopus",
    "doctor octopus (ultimate)",
    "doctor spectrum",
    "doctor strange",
    "doctor strange (ultimate)",
    "dog brother #1",
    "domino",
    "donald blake",
    "doomsday man",
    "doop",
    "doorman",
    "dorian gray",
    "dormammu",
    "dormammu (ultimate)",
    "dr. strange (marvel: avengers alliance)",
    "dracula",
    "dragon lord",
    "dragon man",
    "drax",
    "dreadnoughts",
    "dreaming celestial",
    "druig",
    "dum dum dugan",
    "dust",
    "earthquake",
    "echo",
    "eddie brock",
    "eddie lau",
    "edward \"ted\" forrester",
    "edwin jarvis",
    "ego",
    "electro",
    "electro (ultimate)",
    "elektra",
    "elektra (ultimate)",
    "elements of doom",
    "elite",
    "elixir",
    "elloe kaifi",
    "elsa bloodstone",
    "emma frost",
    "empath",
    "emplate",
    "enchantress (amora)",
    "enchantress (sylvie lushton)",
    "ender wiggin",
    "energizer",
    "epoch",
    "erik the red",
    "eternals",
    "eternity",
    "excalibur",
    "exiles",
    "exodus",
    "expediter",
    "ezekiel",
    "ezekiel stane",
    "fabian cortez",
    "falcon",
    "falcon/sam wilson (maa)",
    "fallen one",
    "famine",
    "fantastic four",
    "fantastic four (ultimate)",
    "fantastick four",
    "fantomex",
    "fat cobra",
    "felicia hardy",
    "fenris",
    "feral",
    "fin fang foom",
    "firebird",
    "firebrand",
    "firedrake",
    "firelord",
    "firestar",
    "firestar (ultimate)",
    "fixer (paul norbert ebersol)",
    "flatman",
    "flying dutchman",
    "foggy nelson",
    "force works",
    "forearm",
    "forge",
    "forge (ultimate)",
    "forgotten one",
    "frank castle",
    "frankenstein's monster",
    "franklin richards",
    "franklin storm",
    "freak",
    "frightful four",
    "frog thor",
    "frog-man",
    "gabe jones",
    "galactus",
    "galia",
    "gambit",
    "gamma corps",
    "gamora",
    "gamora (marvel war of heroes)",
    "gargoyle",
    "gargoyle (yuri topolov)",
    "garia",
    "garrison kane",
    "gateway",
    "gauntlet (joseph green)",
    "geiger",
    "gene sailors",
    "generation x",
    "genesis",
    "genis-vell",
    "george stacy (ultimate)",
    "gertrude yorkes",
    "ghost rider (daniel ketch)",
    "ghost rider (johnny blaze)",
    "ghost rider (marvel war of heroes)",
    "giant girl",
    "giant man",
    "giant-dok",
    "giant-man (ultimate)",
    "gideon",
    "git hoskins",
    "gladiator (kallark)",
    "gladiator (melvin potter)",
    "glenn talbot",
    "glorian",
    "goblin queen",
    "golden guardian",
    "goliath (bill foster)",
    "gorgon",
    "gorilla man",
    "grandmaster",
    "gravity",
    "great lakes avengers",
    "green goblin (barry norman osborn)",
    "green goblin (harry osborn)",
    "green goblin (ultimate)",
    "gressill",
    "grey gargoyle",
    "greymalkin",
    "grim reaper",
    "groot",
    "guardian",
    "guardians of the galaxy",
    "guardsmen",
    "gunslinger",
    "gw bridge",
    "gwen stacy",
    "gwen stacy (ultimate)",
    "h.a.m.m.e.r.",
    "h.e.r.b.i.e.",
    "hairball",
    "half-life (tony masterson)",
    "hammerhead",
    "hammerhead (ultimate)",
    "hank pym",
    "hannibal king",
    "happy hogan",
    "hardball",
    "harley davidson cooper",
    "harpoon",
    "harrier",
    "harry heck",
    "harry osborn",
    "harry osborn (ultimate)",
    "hate-monger (adolf hitler)",
    "havok",
    "hawkeye",
    "hawkeye (kate bishop)",
    "hawkeye (marvel heroes)",
    "hawkeye (ultimate)",
    "hawkeye/clint barton (maa)",
    "hedge knight",
    "hellcat (patsy walker)",
    "hellfire club",
    "hellfire club (ultimate)",
    "hellion",
    "hellions (squad)",
    "hemingway",
    "henry peter gyrich",
    "hepzibah",
    "hercules",
    "heroes for hire",
    "hex",
    "high evolutionary",
    "hindsight lad",
    "hiroim",
    "hitman",
    "hitomi sakuma",
    "hobgoblin (jason macendale)",
    "hobgoblin (robin borne)",
    "hobgoblin (roderick kingsley)",
    "holocaust (age of apocalypse)",
    "holy",
    "hope summers",
    "howard saint",
    "howard the duck",
    "hulk",
    "hulk (has)",
    "hulk (lego marvel super heroes)",
    "hulk (marvel zombies)",
    "hulk (marvel: avengers alliance)",
    "hulk (ultimate)",
    "hulk-dok",
    "hulk/bruce banner (maa)",
    "hulkling",
    "human cannonball",
    "human fly (richard deacon)",
    "human robot",
    "human torch",
    "human torch (jim hammond)",
    "human torch (ultimate)",
    "humbug",
    "husk",
    "hussar",
    "hydra",
    "hydro-man",
    "hyperion (earth-712)",
    "hypno-hustler",
    "iceman",
    "iceman (ultimate)",
    "iceman (x-men: battle of the atom)",
    "ikaris",
    "illuminati",
    "ilyana rasputin",
    "imp",
    "imperfects",
    "imperial guard",
    "impossible man",
    "in-betweener",
    "inertia",
    "infant terrible",
    "inhumans",
    "ink",
    "invaders",
    "invisible woman",
    "invisible woman (marvel: avengers alliance)",
    "invisible woman (ultimate)",
    "iron cross army",
    "iron fist (bei bang-wen)",
    "iron fist (danny rand)",
    "iron fist (orson randall)",
    "iron fist (quan yaozu)",
    "iron fist (usm)",
    "iron fist (wu ao-shi)",
    "iron lad",
    "iron man",
    "iron man (iron man 3 - the official game)",
    "iron man (lego marvel super heroes)",
    "iron man (marvel heroes)",
    "iron man (marvel war of heroes)",
    "iron man (ultimate)",
    "iron man/tony stark (maa)",
    "iron monger",
    "iron patriot",
    "iron patriot (james rhodes)",
    "ironclad",
    "j. jonah jameson",
    "jack flag",
    "jack murdock",
    "jack o' lantern",
    "jack power",
    "jackal",
    "jackpot",
    "james buchanan barnes",
    "james howlett",
    "jamie braddock",
    "jane foster",
    "janus, the nega-man",
    "jasper sitwell",
    "jazinda",
    "jean grey",
    "jean grey",
    "jean grey (ultimate)",
    "jennifer smith",
    "jeryn hogarth",
    "jessica drew",
    "jessica jones",
    "jetstream",
    "jigsaw",
    "jimmy woo",
    "joan the mouse",
    "jocasta",
    "john farson",
    "john jameson",
    "john porter",
    "john wraith",
    "johnny blaze",
    "johnny storm",
    "joseph",
    "joshua kane",
    "josiah x",
    "joystick",
    "jubilee",
    "jubilee (age of apocalypse)",
    "juggernaut",
    "jule carpenter",
    "julian keller",
    "junta",
    "justice",
    "justin hammer",
    "ka-zar",
    "kabuki",
    "kang",
    "karen o'malley",
    "karen page",
    "karma",
    "karnak",
    "karolina dean ",
    "kat farrell",
    "kate bishop",
    "katie power",
    "ken ellis",
    "khan",
    "kid colt",
    "killer shrike",
    "killmonger",
    "killraven",
    "king bedlam",
    "king cobra",
    "kingpin",
    "kinsey walden",
    "kitty pryde",
    "kitty pryde (x-men: battle of the atom)",
    "klaw",
    "komodo (melati kusuma)",
    "korath",
    "korg",
    "korvac",
    "kraven the hunter",
    "kree",
    "krista starr",
    "kronos",
    "kulan gath",
    "kylun",
    "la nuit",
    "lady bullseye",
    "lady deathstrike",
    "lady mastermind",
    "lady ursula",
    "lady vermin",
    "lake",
    "landau",
    "lava-man",
    "layla miller",
    "leader",
    "leech",
    "legion",
    "lei kung, the thunderer",
    "lenny balinger",
    "leo (zodiac)",
    "leopardon",
    "leper queen",
    "lester",
    "lethal legion",
    "lieutenant marcus stone",
    "lifeguard",
    "lightning lords of nepal",
    "lightspeed",
    "lila cheney",
    "lilandra",
    "lilith",
    "lily hollister",
    "lionheart",
    "living lightning",
    "living mummy",
    "living tribunal",
    "liz osborn",
    "lizard",
    "lizard (ultimate)",
    "loa",
    "lockheed",
    "lockjaw",
    "logan",
    "loki",
    "loki (lego marvel super heroes)",
    "loners",
    "longshot",
    "longshot (ultimate)",
    "lord hawal",
    "lord tyger",
    "lords of avalon",
    "lorna dane",
    "luckman",
    "lucky pierre",
    "lucy in the sky",
    "luke cage",
    "luminals",
    "lyja",
    "m (monet st. croix)",
    "m.o.d.a.m.",
    "m.o.d.o.g.",
    "m.o.d.o.k.",
    "m.o.d.o.k. (iron man 3 - the official game)",
    "ma gnuci",
    "mac gargan",
    "mach iv",
    "machine man",
    "mad thinker",
    "madame hydra",
    "madame masque",
    "madame web (julia carpenter)",
    "maddog",
    "madelyne pryor",
    "madripoor",
    "madrox",
    "maelstrom",
    "maestro",
    "magdalene",
    "maggott",
    "magik (amanda sefton)",
    "magik (illyana rasputin)",
    "maginty",
    "magma (amara aquilla)",
    "magneto",
    "magneto (age of apocalypse)",
    "magneto (house of m)",
    "magneto (ultimate)",
    "magneto (x-men: battle of the atom)",
    "magus (adam warlock)",
    "magus (technarch)",
    "major mapleleaf",
    "makkari",
    "malcolm colcord",
    "malice (earth-161)",
    "man-thing",
    "man-wolf",
    "mandarin",
    "mandrill",
    "mandroid",
    "manta",
    "mantis",
    "marauders",
    "marcus van sciver",
    "maria hill",
    "mariko yashida",
    "marrow",
    "marten broadcloak",
    "martin li",
    "marvel apes",
    "marvel boy",
    "marvel zombies",
    "marvex",
    "mary jane watson",
    "mary jane watson (house of m)",
    "mary jane watson (ultimate)",
    "masked marvel (unrevealed)",
    "masque",
    "master chief",
    "master mold",
    "mastermind",
    "masters of evil",
    "mathemanic",
    "matsu'o tsurayaba",
    "matthew murdock",
    "mattie franklin",
    "mauler",
    "maverick (chris bradley)",
    "maverick (christoph nord)",
    "maximus",
    "may parker",
    "medusa",
    "meggan",
    "meltdown",
    "menace",
    "mentallo",
    "mentor",
    "mephisto",
    "mephistopheles",
    "mercury",
    "mesmero",
    "metal master",
    "meteorite",
    "mi: 13",
    "micro/macro",
    "microbe",
    "microchip",
    "micromax",
    "midnight (earth-811)",
    "miek",
    "mikhail rasputin",
    "millenium guard",
    "millie the model",
    "mimic",
    "mindworm",
    "miracleman",
    "miss america",
    "mister fear",
    "mister sinister",
    "mister sinister (deadpool)",
    "mister sinister (house of m)",
    "mister sinister (ultimate)",
    "misty knight",
    "mockingbird",
    "moira mactaggert",
    "moira mactaggert (ultimate)",
    "mojo",
    "mole man",
    "molecule man",
    "molly hayes",
    "molly von richtofen",
    "molten man",
    "mongoose",
    "mongu (unrevealed)",
    "monster badoon",
    "moon knight",
    "moon knight (house of m)",
    "moon knight (ultimate)",
    "moondragon",
    "moonstone",
    "morbius",
    "mordo",
    "morg",
    "morgan stark",
    "morlocks",
    "morlun",
    "morph",
    "mother askani",
    "mr. bumpo",
    "mr. fantastic",
    "mr. fantastic (ultimate)",
    "mr. fish",
    "mr. fixit",
    "mr. hyde",
    "mr. immortal",
    "mr. meugniot",
    "mr. negative",
    "mr. payback",
    "mr. x",
    "ms. marvel (kamala khan)",
    "ms2",
    "mulholland black",
    "multiple man",
    "mvp",
    "mysterio",
    "mysterio (daniel berkhart)",
    "mysterio (francis klum)",
    "mystique",
    "mystique (age of apocalypse)",
    "mystique (house of m)",
    "mystique (ultimate)",
    "nakia (nakia)",
    "namor",
    "namora",
    "namorita",
    "naoko",
    "natasha romanoff",
    "nebula",
    "nehzno",
    "nekra",
    "nemesis",
    "network",
    "new goblin",
    "new mutants",
    "new warriors",
    "new x-men",
    "newton destine",
    "next avengers",
    "nextwave",
    "nick fury",
    "nick fury (lego marvel super heroes)",
    "nick fury (ultimate)",
    "nico minoru",
    "nicolaos",
    "night nurse (earth-9997)",
    "night thrasher",
    "night thrasher (dwayne taylor)",
    "nightcrawler",
    "nightcrawler (ultimate)",
    "nighthawk",
    "nightmare",
    "nightshade",
    "nine-fold daughters of xao",
    "nitro",
    "nocturne",
    "nomad",
    "nomad (rikki barnes)",
    "nomad (steve rogers)",
    "norman osborn",
    "norrin radd",
    "northstar",
    "nova",
    "nova (frankie raye)",
    "nova (sam alexander)",
    "nova (usm)",
    "nuke",
    "obadiah stane",
    "odin",
    "ogun",
    "okoye",
    "old lace",
    "omega flight",
    "omega red",
    "omega sentinel",
    "omega the unknown",
    "onslaught",
    "onslaught (ultimate)",
    "oracle",
    "ord",
    "orphan",
    "orphan-maker",
    "otto octavius",
    "outlaw kid",
    "overlord",
    "owl",
    "ozymandias",
    "paibok",
    "paladin",
    "pandemic",
    "paper doll",
    "patch",
    "patriot",
    "payback",
    "penance (robert baldwin)",
    "pepper potts",
    "pestilence",
    "pet avengers",
    "pete wisdom",
    "peter parker",
    "peter quill",
    "phalanx",
    "phantom reporter",
    "phil coulson (phil coulson)",
    "phil sheldon",
    "photon",
    "phyla-vell",
    "piledriver",
    "pip",
    "pixie",
    "plazm",
    "polaris",
    "post",
    "power man (usm)",
    "power pack",
    "praxagora",
    "preak",
    "pretty boy",
    "pride",
    "prima",
    "prince of orphans",
    "princess powerful",
    "prism",
    "prodigy",
    "proemial gods",
    "professor monster",
    "professor x",
    "professor x (ultimate)",
    "proteus",
    "proteus (house of m)",
    "proteus (ultimate)",
    "proudstar",
    "prowler",
    "prowler (rick lawson)",
    "psycho-man",
    "psylocke",
    "psynapse",
    "puck",
    "puck (zuzha yu)",
    "puff adder",
    "pug",
    "puma",
    "punisher",
    "punisher (2099)",
    "punisher (marvel: avengers alliance)",
    "puppet master",
    "purifiers",
    "purple man",
    "pyro",
    "quake (daisy johnson)",
    "quasar (phyla-vell)",
    "quasar (wendell vaughn)",
    "quasimodo",
    "queen noir",
    "quentin quire",
    "quicksilver",
    "quicksilver (age of apocalypse)",
    "quicksilver (ultimate)",
    "rachel grey",
    "radioactive man",
    "rafael vega",
    "rage",
    "raider",
    "randall",
    "randall flagg",
    "random",
    "rattler",
    "ravenous",
    "rawhide kid",
    "raza",
    "reaper",
    "reavers",
    "reavers (ultimate)",
    "red 9",
    "red ghost",
    "red ghost (ultimate)",
    "red hulk",
    "red hulk (has)",
    "red she-hulk",
    "red shift",
    "red skull",
    "red skull (albert malik)",
    "red wolf",
    "redwing",
    "reptil",
    "retro girl",
    "revanche",
    "rhino",
    "rhodey",
    "richard fisk",
    "rick jones",
    "rick jones (ultimate)",
    "ricochet",
    "rictor",
    "riptide",
    "risque",
    "robbie robertson",
    "robert baldwin ",
    "robin chapel",
    "rocket raccoon",
    "rocket raccoon (marvel heroes)",
    "rocket racer",
    "rockslide",
    "rogue",
    "rogue (age of apocalypse)",
    "rogue (deadpool)",
    "rogue (ultimate)",
    "rogue (x-men: battle of the atom)",
    "roland deschain",
    "romulus",
    "ronan",
    "roughhouse",
    "roulette",
    "roxanne simpson",
    "rumiko fujikawa",
    "runaways",
    "russian",
    "s.h.i.e.l.d.",
    "sabra",
    "sabretooth",
    "sabretooth (age of apocalypse)",
    "sabretooth (house of m)",
    "sabretooth (ultimate)",
    "sage",
    "salem's seven (ultimate)",
    "sally floyd",
    "salo",
    "sandman",
    "santa claus",
    "saracen (muzzafar lambert)",
    "sasquatch (walter langkowski)",
    "satana",
    "sauron",
    "scalphunter",
    "scarecrow (ebenezer laughton)",
    "scarlet spider (ben reilly)",
    "scarlet spider (kaine)",
    "scarlet witch",
    "scarlet witch (age of apocalypse)",
    "scarlet witch (marvel heroes)",
    "scarlet witch (ultimate)",
    "scorpion (carmilla black)",
    "scorpion (ultimate)",
    "scourge",
    "scrambler",
    "scream (donna diego)",
    "screwball",
    "sebastian shaw",
    "secret warriors",
    "selene",
    "senator kelly",
    "sentinel",
    "sentinels",
    "sentry (robert reynolds)",
    "ser duncan",
    "serpent society",
    "sersi",
    "shadow king",
    "shadow king (age of apocalypse)",
    "shadowcat",
    "shadowcat (age of apocalypse)",
    "shadowcat (ultimate)",
    "shadu the shady",
    "shalla-bal",
    "shaman",
    "shane yamada-jones",
    "shang-chi",
    "shang-chi (ultimate)",
    "shanna the she-devil",
    "shape",
    "shard",
    "sharon carter",
    "sharon ventura",
    "shatterstar",
    "she-hulk (has)",
    "she-hulk (jennifer walters)",
    "she-hulk (lyra)",
    "she-hulk (marvel war of heroes)",
    "she-hulk (ultimate)",
    "shen",
    "sheva callister",
    "shi'ar",
    "shinko yamashiro",
    "shinobi shaw",
    "shiva",
    "shiver man",
    "shocker (herman schultz)",
    "shockwave",
    "shooting star",
    "shotgun",
    "shriek",
    "sif",
    "silhouette",
    "silk fever",
    "silver centurion",
    "silver fox",
    "silver sable",
    "silver samurai",
    "silver samurai (age of apocalypse)",
    "silver surfer",
    "silverclaw",
    "silvermane",
    "sin",
    "sinister six",
    "sir ram",
    "siren (earth-93060)",
    "sister grimm",
    "skaar",
    "skaar (has)",
    "skin",
    "skreet",
    "skrulls",
    "skrulls (ultimate)",
    "skullbuster (cylla markham)",
    "slapstick",
    "slayback",
    "sleeper",
    "sleepwalker",
    "slipstream",
    "slyde",
    "smasher (vril rokk)",
    "smiling tiger",
    "snowbird",
    "solo (james bourne)",
    "songbird",
    "sons of the tiger",
    "spacker dave",
    "spectrum",
    "speed",
    "speed demon",
    "speedball (robert baldwin)",
    "spencer smythe",
    "sphinx (anath-na mut)",
    "spider-dok",
    "spider-girl (anya corazon)",
    "spider-girl (may parker)",
    "spider-ham (larval earth)",
    "spider-man",
    "spider-man (1602)",
    "spider-man (2099)",
    "spider-man (ai apaec)",
    "spider-man (ben reilly)",
    "spider-man (house of m)",
    "spider-man (lego marvel super heroes)",
    "spider-man (marvel zombies)",
    "spider-man (marvel: avengers alliance)",
    "spider-man (miles morales)",
    "spider-man (noir)",
    "spider-man (takuya yamashiro)",
    "spider-man (ultimate)",
    "spider-woman (charlotte witter)",
    "spider-woman (jessica drew)",
    "spider-woman (mattie franklin)",
    "spiral (rita wayword)",
    "spirit",
    "spitfire",
    "spot",
    "sprite",
    "spyke",
    "squadron sinister",
    "squadron supreme (earth-712)",
    "squirrel girl",
    "stacy x",
    "stacy x (ultimate)",
    "star brand",
    "star-lord (peter quill)",
    "starbolt",
    "stardust",
    "starfox",
    "starhawk (stakar ogord)",
    "starjammers",
    "stark industries",
    "stature",
    "steel serpent (davos)",
    "stellaris",
    "stepford cuckoos",
    "stephanie de la spiroza",
    "stephen strange",
    "steve rogers",
    "stick",
    "stilt-man (wibur day)",
    "stingray (walter newell)",
    "stone men",
    "storm",
    "storm (age of apocalypse)",
    "storm (marvel heroes)",
    "storm (ultimate)",
    "stranger",
    "strong guy",
    "stryfe",
    "stryfe (ultimate)",
    "sub-mariner",
    "sue storm",
    "sugar man",
    "sumo",
    "sunfire",
    "sunfire (age of apocalypse)",
    "sunset bain",
    "sunspot",
    "super hero squad",
    "super-adaptoid",
    "super-skrull",
    "supernaut",
    "supreme intelligence",
    "surge",
    "susan delgado",
    "swarm",
    "sway",
    "switch",
    "swordsman",
    "swordsman (jaques duquesne)",
    "sym",
    "synch",
    "t'challa",
    "tag",
    "talisman (elizabeth twoyoungmen)",
    "talkback (chase stein)",
    "talon (fraternity of raptors)",
    "talos",
    "tana nile",
    "tarantula (luis alvarez)",
    "tarot",
    "taskmaster",
    "tattoo",
    "ted forrester",
    "tempest",
    "tenebrous",
    "terrax",
    "terror",
    "texas twister",
    "thaddeus ross",
    "thanos",
    "thanos (ultimate)",
    "the 198",
    "the anarchist",
    "the call",
    "the captain",
    "the enforcers",
    "the executioner",
    "the fallen",
    "the fury",
    "the hand",
    "the hood",
    "the howling commandos",
    "the hunter",
    "the initiative",
    "the leader (has)",
    "the liberteens",
    "the liberty legion",
    "the order",
    "the phantom",
    "the professor",
    "the renegades",
    "the santerians",
    "the shiver man",
    "the spike",
    "the stranger",
    "the twelve",
    "the watchers",
    "thena",
    "thing",
    "thing (marvel heroes)",
    "thing (ultimate)",
    "thor",
    "thor (goddess of thunder)",
    "thor (maa)",
    "thor (marvel heroes)",
    "thor (marvel war of heroes)",
    "thor (marvel: avengers alliance)",
    "thor (ultimate)",
    "thor girl",
    "thunderball",
    "thunderbird (john proudstar)",
    "thunderbird (neal shaara)",
    "thunderbolt (bill carver)",
    "thunderbolt ross",
    "thunderbolts",
    "thundra",
    "tiger shark",
    "tiger's beautiful daughter",
    "tigra (greer nelson)",
    "timeslip",
    "tinkerer",
    "tippy toe",
    "titania",
    "titanium man (topolov)",
    "toad",
    "toad men",
    "tomas",
    "tombstone",
    "tomorrow man",
    "tony stark",
    "toro (thomas raymond)",
    "toxin",
    "toxin (eddie brock)",
    "trauma",
    "triathlon",
    "trish tilby",
    "triton",
    "true believers",
    "turbo",
    "tusk",
    "two-gun kid",
    "tyger tiger",
    "typhoid mary",
    "tyrannus",
    "u-foes",
    "u-go girl",
    "u.s. agent",
    "uatu the watcher",
    "ulik",
    "ultimate spider-man (usm)",
    "ultimates",
    "ultimatum",
    "ultimo",
    "ultra-adaptoid",
    "ultragirl (earth-93060)",
    "ultron",
    "umar",
    "unicorn",
    "union jack (brian falsworth)",
    "union jack (joseph chapman)",
    "union jack (montgomery falsworth)",
    "unus",
    "unus (age of apocalypse)",
    "unus (house of m)",
    "unus (ultimate)",
    "valeria richards",
    "valkyrie (samantha parrington)",
    "valkyrie (ultimate)",
    "vampiro",
    "vance astro",
    "vanisher (age of apocalypse)",
    "vanisher (telford porter)",
    "vanisher (ultimate)",
    "vapor",
    "vargas",
    "vector",
    "veda",
    "vengeance (michael badilino)",
    "venom (flash thompson)",
    "venom (mac gargan)",
    "venom (ultimate)",
    "venus (siren)",
    "venus dee milo",
    "vermin (edward whelan)",
    "vertigo (savage land mutate)",
    "victor mancha",
    "victor von doom",
    "vin gonzales",
    "vindicator",
    "violations",
    "viper",
    "virginia dare",
    "vision",
    "vivisector",
    "vulcan (gabriel summers)",
    "vulture (adrian toomes)",
    "vulture (blackie drago)",
    "wallflower",
    "wallop",
    "wallow",
    "war (abraham kieros)",
    "war machine (iron man 3 - the official game)",
    "war machine (marvel: avengers alliance)",
    "war machine (parnell jacobs)",
    "war machine (ultimate)",
    "warbird",
    "warbound",
    "warhawk (mitchell tanner)",
    "warlock (janie chin)",
    "warlock (technarchy)",
    "warpath",
    "warren worthington iii",
    "warstar",
    "wasp",
    "wasp (ultimate)",
    "weapon omega",
    "weapon x",
    "wendell rand",
    "wendell vaughn",
    "wendigo",
    "werewolf by night",
    "whiplash (mark scarlotti)",
    "whirlwind",
    "whistler",
    "white queen (adrienne frost)",
    "white tiger (angela del toro)",
    "white tiger (usm)",
    "whizzer (stanley stewart)",
    "wiccan",
    "wild child",
    "wild child (age of apocalypse)",
    "wild pack",
    "wildside",
    "william stryker",
    "wilson fisk",
    "wind dancer",
    "winter soldier",
    "wither",
    "wolf cub",
    "wolfpack",
    "wolfsbane",
    "wolfsbane (age of apocalypse)",
    "wolver-dok",
    "wolverine",
    "wolverine (lego marvel super heroes)",
    "wolverine (marvel war of heroes)",
    "wolverine (ultimate)",
    "wolverine (x-men: battle of the atom)",
    "wonder man",
    "wong",
    "wong (ultimate)",
    "wraith",
    "wrecker",
    "wrecking crew",
    "x-23",
    "x-51",
    "x-babies",
    "x-cutioner",
    "x-factor",
    "x-factor investigations",
    "x-force",
    "x-man",
    "x-men",
    "x-men (ultimate)",
    "x-ray (james darnell)",
    "x-statix",
    "x.s.e.",
    "xavin",
    "xorn (kuan-yin xorn)",
    "yellow claw",
    "yellowjacket (rita demara)",
    "young avengers",
    "young x-men",
    "zaladane",
    "zaran",
    "zarda",
    "zarek",
    "zeigeist",
    "zemo",
    "zodiak",
    "zombie (simon garth)",
    "zuras",
    "zzzax"
]

  
